export const FETCH_USERDATA_BEGINS = "FETCH_USERDATA_BEGINS";
export const FETCH_USERDATA_SUCCESS = "FETCH_USERDATA_SUCCESS";
export const FETCH_USERDATA_ERROR = "FETCH_USERDATA_ERROR";

export const SAVE_RIDE = "SAVE_RIDE";

export const FETCH_HOME_BEGINS = "FETCH_HOME_BEGINS";
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS";
export const FETCH_HOME_ERROR = "FETCH_HOME_ERROR";

export const DELETE_HOME = "DELETE_HOME";

export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION";
export const CURRENT_LOCATION_ERROR = "CURRENT_LOCATION_ERROR";

export const UPDATE_PROFILE_BEGINS = "UPDATE_PROFILE_BEGINS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";