export const FETCH_USERDATA_BEGINS = "FETCH_USERDATA_BEGINS";
export const FETCH_USERDATA_SUCCESS = "FETCH_USERDATA_SUCCESS";
export const FETCH_USERDATA_ERROR = "FETCH_USERDATA_ERROR";
export const SAVE_RIDE = "SAVE_RIDE";
