export const FETCH_USERDATA_BEGINS = "FETCH_USERDATA_BEGINS";
export const FETCH_USERDATA_SUCCESS = "FETCH_USERDATA_SUCCESS";
export const FETCH_USERDATA_ERROR = "FETCH_USERDATA_ERROR";
export const SAVE_RIDE = "SAVE_RIDE";
export const FETCH_HOME_BEGINS = "FETCH_HOME_BEGINS";
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS";
export const FETCH_HOME_ERROR = "FETCH_HOME_ERROR";
